import ReactMarkdown from "react-markdown";
import { X, Brain, Loader2, Sparkles } from "lucide-react";
import { useEffect } from "react";

interface AIAnalysisModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: string | null;
  isLoading: boolean;
  symbol: string;
  title?: string;
  subtitle?: string;
}

export default function AIAnalysisModal({
  isOpen,
  onClose,
  analysis,
  isLoading,
  symbol,
  title = "Gemini AI Deep Analysis",
  subtitle,
}: AIAnalysisModalProps) {
  // Prevent scroll when open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "unset";
    }
    return () => {
      document.body.style.overflow = "unset";
    };
  }, [isOpen]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-surface-0/80 backdrop-blur-sm animate-fade-in">
      <div className="relative w-full max-w-4xl max-h-[90vh] bg-surface-1 border border-border-default rounded-2xl shadow-2xl flex flex-col overflow-hidden animate-slide-up">
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-border-subtle bg-surface-2/50 shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-accent-cyan/10 flex items-center justify-center text-accent-cyan">
              <Brain size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-text-primary flex items-center gap-2">
                {title}
                <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-surface-3 text-text-muted border border-border-subtle uppercase tracking-widest">
                  1.5 FLASH
                </span>
              </h2>
              <p className="text-xs text-text-secondary mt-0.5">
                {subtitle || (
                  <>
                    Multi-dimensional insights for{" "}
                    <span className="text-accent-cyan font-bold">{symbol}</span>
                  </>
                )}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg text-text-muted hover:text-text-primary hover:bg-surface-3 transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 sm:p-8 custom-scrollbar bg-surface-1/50">
          {isLoading ? (
            <div className="h-64 flex flex-col items-center justify-center gap-4">
              <div className="relative">
                <Loader2 size={48} className="text-accent-cyan animate-spin" />
                <Sparkles
                  size={20}
                  className="text-accent-violet absolute top-0 right-0 animate-pulse"
                />
              </div>
              <div className="text-center">
                <p className="text-text-primary font-medium animate-pulse">
                  Synthesisng analysis...
                </p>
                <p className="text-xs text-text-muted mt-1 italic">
                  Processing news data, technical indicators, and market
                  sentiment.
                </p>
              </div>
            </div>
          ) : analysis ? (
            <article
              className="prose prose-invert max-w-none 
              prose-headings:text-text-primary prose-headings:font-bold prose-headings:mt-8 prose-headings:mb-4
              prose-h1:text-2xl prose-h2:text-xl prose-h3:text-lg
              prose-p:text-text-secondary prose-p:leading-relaxed prose-p:mb-4
              prose-strong:text-accent-cyan prose-strong:font-semibold
              prose-ul:list-disc prose-ul:pl-5 prose-ul:mb-4 prose-ul:space-y-2
              prose-li:text-text-secondary
              prose-hr:border-border-subtle prose-hr:my-8
            "
            >
              <ReactMarkdown>{analysis}</ReactMarkdown>
            </article>
          ) : (
            <div className="text-center py-12">
              <p className="text-text-muted">
                Failed to generate analysis. Please try again.
              </p>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-border-subtle bg-surface-2/30 flex justify-between items-center shrink-0">
          <p className="text-[10px] text-text-muted italic">
            This analysis is generated by AI for informational purposes only.
            Not financial advice.
          </p>
          <button
            onClick={onClose}
            className="px-6 py-2 rounded-lg bg-surface-3 hover:bg-surface-4 text-text-primary text-sm font-medium transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
